# バイオプログラミング第2 第五回演習

## 課題1
次の連立方程式をnumpyを使って解け。
$$
\left\{
  \begin{array}{rcl}
    2x - 3y + z &=& 1 \\
    x + 2y - 3z &=& 4 \\
    3x + 2y - z &=& 5
  \end{array}
\right.
$$

In [1]:
import numpy as np

# Coefficient matrix (A) and right-hand side vector (b)
A = np.array([[2, -3, 1],
              [1, 2, -3],
              [3, 2, -1]])
b = np.array([1, 4, 5])

# Solve the system of linear equations
solution = np.linalg.solve(A, b)
solution

array([ 1.25,  0.25, -0.75])

## 課題2
以下の3つの行基本変形を、正則行列を左からかけることで実現する関数をそれぞれ作成せよ。

1. *i* 行目と *j* 行目を交換する
2. *i* 行目を *c* 倍する（*c*≠0)
3. *j* 行目の *c* 倍を *i* 行目に加える

ただし、関数の引数には *i, j, c* 及び変形を行う numpy 行列を指定せよ (numpy 行列は 3 つの関数を内包するクラスのインスタンス変数としても良い)。また、変形を行う numpy 行列の大きさは可変とする（次元は 2）。

> 出力例:
```python
>> A = np.arange(12).reshape((3, 4))  # 変形を行う行列
>> EM = elementary_matrix(A)  # インスタンス生成
>> EM.trans1(1, 2)  # 行基本変形(1)
array([[ 0.,  1.,  2.,  3.],
       [ 8.,  9., 10., 11.],
       [ 4.,  5.,  6.,  7.]])
```

> ***ヒント***  
> * 生命系の数学の授業で学習したように行基本変形の際にかける正則行列はそれぞれ以下の性質を持つ。
>   1. 単位行列の *i* 行と *j* 行を交換した行列
>   2. 単位行列の *ii* 成分を *c* とした行列
>   3. 単位行列の *ij* 成分を *c* とした行列
>
> * ndarrayをコピーして別の ndarray として扱うには、`numpy.copy` を使用する。Python の代入は参照そのものがコピーされるため変数名を変更したのと同義となる。
```python
# 直接代入した場合
>> x = np.arange(5)
>> y = x
>> y[0] = 100
>> x
array([100, 1, 2, 3, 4])

# copy を利用
>> x = np.arange(5)
>> y = np.copy(x)
>> y[0] = 100
>> x
array([0, 1, 2, 3, 4])
```
```

In [5]:
import numpy as np

class ElementaryMatrix:
    def __init__(self, matrix):
        # 変形対象の行列をコピーして保存
        self.original_matrix = matrix  # 元の行列を保持する
    
    def trans1(self, i, j):
        """i 行目と j 行目を交換する"""
        # 元の行列をコピーして新しい行列を作成
        matrix = np.copy(self.original_matrix)
        n = matrix.shape[0]
        P = np.eye(n)
        P[[i, j]] = P[[j, i]]  # i 行目と j 行目を交換
        # 正則行列を左から掛けて変形
        return P @ matrix

    def trans2(self, i, c):
        """i 行目を c 倍する (c ≠ 0)"""
        # 元の行列をコピーして新しい行列を作成
        matrix = np.copy(self.original_matrix)
        n = matrix.shape[0]
        P = np.eye(n)
        P[i, i] = c  # i 行の対角成分を c に設定
        # 正則行列を左から掛けて変形
        return P @ matrix

    def trans3(self, i, j, c):
        """j 行目の c 倍を i 行目に加える"""
        # 元の行列をコピーして新しい行列を作成
        matrix = np.copy(self.original_matrix)
        n = matrix.shape[0]
        P = np.eye(n)
        P[i, j] = c  # j 行の c 倍を i 行に加える
        # 正則行列を左から掛けて変形
        return P @ matrix


In [6]:
# 例として3×4の行列を作成
A = np.arange(12).reshape((3, 4))

# インスタンス生成
EM = ElementaryMatrix(A)

# 行基本変形 (1): 1行目と2行目の交換
print("1行目と2行目を交換:")
print(EM.trans1(1, 2))

# 行基本変形 (2): 1行目を2倍する
print("\n1行目を2倍:")
print(EM.trans2(1, 2))

# 行基本変形 (3): 2行目の3倍を0行目に加える
print("\n2行目の3倍を0行目に加える:")
print(EM.trans3(0, 2, 3))


1行目と2行目を交換:
[[ 0.  1.  2.  3.]
 [ 8.  9. 10. 11.]
 [ 4.  5.  6.  7.]]

1行目を2倍:
[[ 0.  1.  2.  3.]
 [ 8. 10. 12. 14.]
 [ 8.  9. 10. 11.]]

2行目の3倍を0行目に加える:
[[24. 28. 32. 36.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## 考察